/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#738296",
        "primary-container": "#0f172a",
        "secondary-container": "#00a6e0",
        "inverse-primary": "#565e74",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#798098",
        "tertiary-fixed-dim": "#b9c8de",
        "secondary-fixed-dim": "#7bd0ff",
        "surface-dim": "#101415",
        "on-secondary-fixed-variant": "#004c69",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary-container": "#00374d",
        "on-background": "#e0e3e5",
        tertiary: "#b9c8de",
        surface: "#101415",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "tertiary-container": "#081828",
        "surface-bright": "#363a3b",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "surface-variant": "#323537",
        "inverse-on-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#39485a",
        "on-tertiary-fixed": "#0d1c2d",
        "surface-container-low": "#191c1e",
        "on-tertiary": "#233143",
        "surface-container": "#1d2022",
        "on-primary": "#283044",
        primary: "#bec6e0",
        "on-secondary-fixed": "#001e2c",
        "on-surface": "#e0e3e5",
        "tertiary-fixed": "#d4e4fa",
        "on-error": "#690005",
        "surface-container-high": "#272a2c",
        "secondary-fixed": "#c4e7ff",
        background: "#101415",
        outline: "#909097",
        "surface-tint": "#bec6e0",
        "on-surface-variant": "#c6c6cd",
        "inverse-surface": "#e0e3e5",
        "surface-container-highest": "#323537",
        error: "#ffb4ab",
        "outline-variant": "#45464d",
        "surface-container-lowest": "#0b0f10",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "max-width": "1280px",
        "margin-mobile": "20px",
        unit: "4px",
        "margin-desktop": "80px",
        gutter: "24px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        caption: ["Hanken Grotesk"],
        "label-mono": ["Geist"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "32px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-mono": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
};
